apiVersion: v2
name: mqtt-blackbox-exporter
description: Connect, Subscribe and Publish over MQTT broker to check its status.
home: https://github.com/snapp-incubator/mqtt-blackbox-exporter
sources:
  - https://github.com/snapp-incubator/mqtt-blackbox-exporter.git
maintainers:
  - name: parham alvani
    url: https://github.com/1995parham
    email: parham.alvani@snapp.cab
  - name: amirhossein najafizadeh
    url: https://github.com/amirhnajafiz
type: application
version: 0.0.0
appVersion: latest

