apiVersion: v2
name: mqtt-blackbox-exporter
description: Helm chart for snapp mqtt-blackbox-exporter to check MQTT broker status.
type: application
version: 0.1.0
appVersion: "1.16.0"
maintainers:
  - name: parham alvani
    email: parham.alvani@snapp.cab
deprecated: false
dependencies:
  - name: emqx
    version: 4.2.0
    repository: https://repos.emqx.io/charts
  - name: jaeger
    version: 0.55.0
    repository: https://jaegertracing.github.io/helm-charts