apiVersion: v1
kind: Application
metadata:
  name: mqtt-blackbox-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snapp-incubator/mqtt-blackbox-exporter.git
    targetRevision: HEAD
  destination:
    server: # Where to go?
    namespace: argocd
stringData:
  name: mqtt-blackbox-exporter
  url: https://github.com/snapp-incubator/mqtt-blackbox-exporter/tree/developer/deployment/mqtt-blackbox-exporter
  type: helm